DoSomething/LetsDoThis-iOS

.gitignore
Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Classes/AppDelegate.m
Lets Do This/keys.plist

Fixes #6
Adds a new untracked plist file to store data like API keys, which is populated with dummy data.  Gets us in a good place to start on #3 as well.

Keys.plist

---

Lets Do This/Base.lproj/Main.storyboard
Lets Do This/Controllers/LDTLoginViewController.h
Lets Do This/Controllers/LDTLoginViewController.m
Lets Do This/Controllers/LDTSettingsViewController.m

Adds `resignFirstResponder` to dismiss keyboard, allowing iPhone 5 users to tap the "Sign in" button

Let's Do This logging in thing.

---

Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Base.lproj/Main.storyboard
Lets Do This/Classes/AppDelegate.m
Lets Do This/Controllers/LDTSettingsViewController.m
Lets Do This/Info.plist
Lets Do This/Models/DSOSession.h
Lets Do This/Models/DSOSession.m

Adds a `UISwitch` to indicate whether or not the user has enabled notifications, and displays a popup indicating how to change.
I created a Provisioning Profile for the App Store, and it seems to have resolved the "Missing Push Notification Entitlement - Your app appears to include API used to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlemen" email I received upon submitting builds 1 and 2 for v0.1.1.  However, I can no longer build to my iPhone in Xcode, receiving the error: "A valid provisioning profile for this executable was not found."
Related Trello card: https://trello.com/c/3eetV2oh

Notification Settings

---

Lets Do This/Controllers/LDTTabBarController.m
Lets Do This/Info.plist
Lets Do This/Models/DSOCampaign.h
Lets Do This/Models/DSOCampaign.m

Closes #48: Adds `allCampaigns` method to use the `legacyServerSession` to query the `campaigns` endpoint for all Campaigns featured in the mobile app.
Closes #49: Use new `campaigns` endpoint and response for Campaign objects.

GET campaigns

---

Lets Do This/Controllers/LDTCampaignActionsViewController.m

Closes #57 by conditionally checking for signup status before posting a signup.
First pass at copy for the success message.

Check your signup before you post your signup

---

Lets Do This/LetsDoThis.pch
Podfile

Previously, with MagicalRecord 2.2, the main header file of the Cocoapod [was named `CoreData+MagicalRecord.h`](https://github.com/magicalpanda/MagicalRecord/tree/2.2/MagicalRecord). With the newest stable release, 2.3, the name of this header file [was changed to `MagicalRecord.h`](https://github.com/magicalpanda/MagicalRecord/tree/v2.3.0/MagicalRecord). 
This PR updates where we import this header file. It also specifies the `2.3` version of MagicalRecord.

specify MagicalRecord version, change MagicalRecord header filename

---

Lets Do This/Models/DSOUser.m

Order of operations is off in sync'ing. Refs #65
What happened is my User activity was syncing before the relevant Campaigns were stored into Coredata.

Only add campaign if object exists

---

Lets Do This/Base.lproj/Main.storyboard
Lets Do This/Controllers/LDTCampaignDetailViewController.m
Lets Do This/Controllers/LDTReportbackSubmitViewController.h
Lets Do This/Controllers/LDTReportbackSubmitViewController.m

Adds imagePicker for camera or photo library, and displays the selcted image in the `imageView` outlet.  Doesn't POST the reportback to API yet.
`ALAssetsLibrary` stuff was copied from http://www.raywenderlich.com/forums/viewtopic.php?f=2&p=34901. in the SlothKit to get the name of the selected file (to preserve its file extension).  This library is deprecated and should be replaced by the Photos Framework: https://developer.apple.com/library/ios/documentation/Photos/Reference/Photos_Framework/index.html#//apple_ref/doc/uid/TP40014408

Reportback Submit VC

---

Lets Do This/Base.lproj/Main.storyboard
Lets Do This/Controllers/LDTCampaignDetailViewController.m
Lets Do This/Models/DSOCampaign.h
Lets Do This/Models/DSOCampaign.m

Refs #54
Adds a new `DSOCampaign reportbackItemsWithStatus` method. TBD how to match block syntax of existing API functions.
Displays promoted reportback captions and images as a tiny tiny little `UITableViewCell.imageView`.
Next up is a custom ReportbackItemTableViewCell to display bigger image / better info.

Start of Campaign Reportback gallery

---

Lets Do This/Classes/AppDelegate.m
Lets Do This/Models/DSOSession.m
README.md

Removes `api.dosomething.org` URL in favor of `northstar.dosomething.org` and `northstar-qa.dosomething.org`.
Refactors `northstarApiKey` element in `keys.plist` as `northstarTestKey` and `northstarLiveKey`.
Makes this so much easier to test correctly.
Refs  #93 - still need to determine if we should instead be using the `DSOSessionEnvironment` typedef for this.

Let there be QA

---

Lets Do This/Controllers/Settings/LDTSettingsViewController.m
Lets Do This/Networking/DSOUserManager.m

#505 documented an issue where a user was unable to logout because the logout API call returned an error. 
Now, if the user hits the "logout" button, she'll always be logged out--even if an error is returned by the API. 
Tested by logging in with user A, turning off the wifi (to produce an error for the API, which previously would've prevented logout), and then logging out. Then turning on wifi, logging in user B, and confirming that the user account data belongs to user B. 
Then turning off wifi, logging out, turning on wifi, and logging in with user A again. 
Also tested by logging in with user A, turning off wifi, logging out. Then turning on wifi, logging in with user A again, and confirming that user account data belongs to user A. 
refers to #505.

user tapping logout will always logout, even if error is returned by API

---

Lets Do This/Controllers/Settings/LDTSettingsViewController.m

LDTMessages was changed in #633. In this PR, we update the 
Tested by logging in, turning off connectivity, then attempting to log out, forcing the "Internet is trying to cause drama" error message to appear in the correct view controller. 
This PR precipitated by a conversation in #635:
>@tongxiang Did you test this? I've just tested and the `LDTMessage` is not visible. This method displays the error in the defaultViewController, which is the TabBarController, which sits underneath the presented Settings controller (since it's pushed modally)
>This is caused by changes introduced in #633 -- which allows us to avoid constantly setting the `LDTMessage defaultViewController`.  The fix here is to use the new method `displayErrorInViewController:error`, displaying the message in …

update LDTMessage usage

---

Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Classes/AppDelegate.m
Lets Do This/LetsDoThis.pch
Podfile

Followed [these](https://rpm.newrelic.com/accounts/108038/mobile/setup#tab-ios_tabs=cocoapods) directions to get New Relic reporting for the app up and running. 
Added a new key-value pair to `keys.plist`, `newRelicAppToken`. Will email out the new `keys.plist` file. 
New Relic is able to report from the simulator. Tested by running on multiple devices on the simulator, each which counts as a unique device to New Relic. Checked [this panel](https://rpm.newrelic.com/accounts/108038/mobile?) to make sure the hits showed up. 
Closes #568.

add new relic monitoring

---

Lets Do This/Controllers/Profile/LDTUserProfileViewController.m
Lets Do This/Models/DSOCampaignSignup.h
Lets Do This/Models/DSOUser.h
Lets Do This/Models/DSOUser.m
Lets Do This/Networking/DSOUserManager.m

Closes #385 - The `campaignSignups` should not be a public `NSMutableArray` that any class could add any object into.
* Refactors `campaignSignups` as a readonly `NSArray`. which returns a copy of a new private `NSMutableArray` property, `mutableCampaignSignups` 
* Adds a `removeAllCampaignSignups` method used for scenarios when we want to sync a user's signups (so remove all of them first)
* Adds a `addCampaignSignup:(DSOCampaignSignup *)campaignSignup` method which adds the given Signup to the user's `campaignSignups` array, via `[self.mutableCampaignSignups addObject] `

Set DSOUser.campaignSignups as readonly

---

Lets Do This/Models/DSOCampaign.h
Lets Do This/Models/DSOCampaign.m
Lets Do This/Models/DSOCampaignSignup.m
Lets Do This/Models/DSOReportbackItem.m
Lets Do This/Networking/DSOUserManager.m

Resolves the warnings/todo's to close #301:
* When initializing a `DSOReportbackItem` from a given `NSDictionary` -- use whatever `campaign` object we have stored via new `DSOCampaign` method `-(instancetype)initWithCampaignID:title:`. This is a bit forward thinking for if/when we want to display Reportback Items on User Profiles for Campaigns which have since expired. 
* Adds a `-(DSOCampaign *)campaign` getter method which returns the loaded `DSOCampaign` from the `[DSOUserManager sharedInstance].activeMobileAppCampaigns` if it exists. Else provides the minimal `DSOCampaign` object returned by API. Refs #645 - won't work if we set `self.campaign` instead of `_campaign` within the `initWithDict:` method

Custom accessor for DSOReportbackItem.campaign

---

Lets Do This/Controllers/Campaign/LDTCampaignListViewController.m
Lets Do This/Controllers/Profile/LDTUserProfileViewController.m
Lets Do This/Models/DSOCampaign.h
Lets Do This/Networking/DSOUserManager.m

* Casts `NSInteger` to fix XCode warnings
* Define `DSOCampaign.numberOfDaysLeft` as a readonly property - refs #329

Minor cleanup

---

Lets Do This/Views/Base/LDTTheme.m

I've gone through each of the method declarations and implementations in our codebase, and just made one change removing linebreaks to the `LDTTheme` file. 
Closes #312.

remove linebreaks for method declarations / implementations/ calls

---

Lets Do This/Models/DSOUser.m

Previously, we'd see an error logged on signin: "Failed to persist photo data to disk". This indicated that the `[photoData writeToFile:storedAvatarPhotoPath atomically:NO]` was returning a `0` value, meaning that it failed to persist the photo data to disk. 
This was happening when your own user object was initialized within `DSOUser initWithDict`. When `self.photo = nill` is set on line 50, we all `DSOUser setPhoto` which then calls `DSOUserManager storeAvatar`. This returns an error with `[photoData writeToFile:storedAvatarPhotoPath atomically:NO]` because the `photo` param we're attempting to store is `nil`. 
Now, we check within `DSOUser setPhoto` whether the `photo` param is nil before storing it as the user's avatar. 
Tested with two accounts on prod, `tong@x.co` and …

remove falsely logged error "Failed to persist photo data to disk"

---

Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Controllers/Profile/LDTUserProfileViewController.m
Lets Do This/Views/Profile/LDTProfileCampaignTableViewCell.h
Lets Do This/Views/Profile/LDTProfileCampaignTableViewCell.m
Lets Do This/Views/Profile/LDTProfileCampaignTableViewCell.xib
Lets Do This/Views/Profile/LDTProfileHeaderTableViewCell.h
Lets Do This/Views/Profile/LDTProfileHeaderTableViewCell.m
Lets Do This/Views/Profile/LDTProfileHeaderTableViewCell.xib
Lets Do This/Views/Profile/LDTProfileNoSignupsTableViewCell.h
Lets Do This/Views/Profile/LDTProfileNoSignupsTableViewCell.m
Lets Do This/Views/Profile/LDTProfileNoSignupsTableViewCell.xib
Lets Do This/Views/Profile/LDTUserProfileView.xib

Closes #418 
* Renders existing User Profile header, using `UITableViewCell` instead of a `UIView`. This makes the header scrollable (was previously static on top of the screen)
* Fixes profile design by moving it up vertically, behind the navigation bar.  This makes it a little more difficult to click with the changes we made in #636 - only the bottom half of the avatar is clikcable (cc @lkpttn )
* Adds user country to the header
* Starts on the No Campaigns view -- button not added yet and styles not finished. Debating on refactoring the `LDTEpicFailView` to be reusable, so we can use here and in handling Campaign Detail edge cases as well
Missing a "Take me there" button to open the first Actions tab
Missing a "Go back" button to pop back to previous screen. This will occur when the …

Refactor Profile header, start on No Campaigns view

---

Lets Do This/Controllers/Profile/LDTUserProfileViewController.m

Fixes #653. Same deal as `LDTCampaignDetailViewController` in #615

Hide Profile navigationBar on scroll

---

Lets Do This/Controllers/Profile/LDTProfileViewController.m

Fixes #669 - uses same logic as Campaign Detail does, checking for whether or not the given `DSOReportbackItem` has an `image` property set -- and displaying it if we do instead of checking for the `imageURL`.

Fix missing Profile Reportback image after just submitting

---

Lets Do This/Controllers/Profile/LDTProfileViewController.m

Fixes #665 by additionally checking to see if the User the Profile VC is initialized with is our logged in user. Also cleans up all conditionals to just check for `self.isCurrentUserProfile` to keep things consistent.

Fix for viewing your own Profile from a Reportback Detail

---

Lets Do This/Controllers/Campaign/LDTCampaignListViewController.m

Fixes #674 - Refactors `- (void)createInterestGroups` as `- (BOOL)loadInterestGroups`. Only reload the `LDTCampaignListViewController.collectionView` when `loadInterestGroups` succeeds.

Campaign Detail - loadInterestGroups

---

Lets Do This/Controllers/Base/LDTTabBarController.m

Changes the `LDTTabBarController` tint color to `LDTTheme.ctaBlueColor`. 
Closes #671.

change LDTTabBarController color to LDTTheme.ctaBlueColor

---

Lets Do This/Controllers/Campaign/LDTCampaignDetailViewController.m

Cleanup task from #685 -- refactors `configureReportbackItemDetailView:forIndexPath:` and `configureSelfReportbackCell:` to DRY.

configureReportbackItemCell:forIndexPath:

---

Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Categories/NSDate+DSO.h
Lets Do This/Categories/NSDate+DSO.m
Lets Do This/Categories/NSDictionary+DSOJsonHelper.h
Lets Do This/Categories/NSDictionary+DSOJsonHelper.m
Lets Do ThisTests/NSDate+DSOTests.m
Lets Do ThisTests/NSDictionary+DSOJsonHelperTests.m

Removes functions unused by `NSDictionary+DSOJsonHelper` and `NSDate+DSO`, adds tests to `NSDate+DSO`. 
Manually tested by running all tests, and building and running app. 
Closes #371.

remove unused functions, add NSDate+DSOTests

---

Lets Do This/Controllers/Login/LDTUserRegisterViewController.m
Lets Do This/Controllers/Reportback/LDTSubmitReportbackViewController.m
Lets Do This/Views/Reportback/LDTSubmitReportbackView.xib
Podfile

Adds a check to make sure that the reportback quantity submitted is less than or equal to `2147483647`, the largest 32 bit integer. If the user inputs a number greater than that value, the "submit" button will be deactivated. Also checks to make sure emoji haven't been input in the caption text fields. 
Also adds similar form validation as `LDTUserRegisterViewController.m`. 
Tested the limits of the reportback quantity validation--adding a caption that's greater than 60 characters, no caption, a quantity greater than `2147483647`, or a quantity less than 1. 
Tested the emoji validations by entering emoji in the requisite text fields. 
The largest reportback integer which can be handled by Phoenix is `2147483647`. By adding this check to the reportback submission controller, we prevent the …

add check for reportback quantity numbers greater than 2147483647 in submission controller

---

Lets Do This/Controllers/Login/LDTUserRegisterViewController.m

Makes the register view controller just a little bit DRY-er by adding the `validatePassword` call. 
Tested by running through the register process. 
Closes #684.

Validate password

---

Lets Do This/Views/Settings/LDTSettingsView.xib

Adds a trailing constraint to the `UILabel` displaying "Logged in as <email username>"  on the settings page. Now, extremely long email addresses will be truncated by ellipses. 
Tested by logging in as a user with an extremely long username. My account, created on staging: 
username: tongxiangtongxiangtongxiangtongxiangtongxiang@dosomething.org 
password: < summer ball pasttime of dosomething staffers >
Closes #654. 
The new look:

add trailing constraint to "logged in email label"

---

Lets Do This/LetsDoThis.pch

Adds a clarifying comment to the `LetsDoThis.pch` file about where frameworks are being imported from. #### What are the relevant tickets?
Closes #429.

add clarifying import comment to LetsDoThis.pch

---

Lets Do This/Controllers/Base/LDTBaseViewController.m
Lets Do This/Controllers/Login/LDTUserRegisterViewController.m
Lets Do This/Controllers/Reportback/LDTSubmitReportbackViewController.m

1. Adds character restrictions (the text field will not accept any added characters beyond the 60th character added) to the caption field in the submit reportback view, and email field in the register view. 
2. Adds error messages which appear when the user attempts to input more than 60 characters in either field. 
Tested by attempting to add more than 60 characters to both of the text fields above. Also tested the other text fields on the screen, to ensure that they wouldn't be restricted. 
In order to make sure that the UITextField delegate method only restricts input for the fields we want it to restrict input for, we had to 1) assign tags to each UITextField, 2) create a dictionary of tag-UITextField key-value pairs, and 3) use this dictionary to check for the right UITextField each …

add char restrictions to input and error messaging to register and submit reportback

---

Lets Do This/Views/Campaign/LDTCampaignDetailCampaignCell.m

Per http://stackoverflow.com/a/26349770/1470725 which suggests that `preferredLayoutAttributesFittingAttributes` is red herring... seems like it is. If I remove it completely, the Campaign Detail Campaign Cell still self sizes. Looked into this while reading up and troubleshooting #701. 
refs #480 which introduced the method based on other threads (links in its description)

Removes unnecessary preferredLayoutAttributesFittingAttributes

---

Lets Do This/Controllers/Campaign/LDTCampaignDetailViewController.m
Lets Do This/Views/Campaign/LDTCampaignDetailCampaignCell.h
Lets Do This/Views/Campaign/LDTCampaignDetailCampaignCell.m
Lets Do This/Views/Campaign/LDTCampaignDetailCampaignCell.xib

Refs #697: Implements self sizing Campaign Detail presignup cell 
Refs https://github.com/DoSomething/LetsDoThis-iOS/pull/701#issuecomment-166373083 -- Use the `LDTCampaignDetailCampaignCell` (which is currently self sizing) to render the presignup view (by collapsing the Do It Container `UIView`). 
This is working! Used the ol' priority trick to fix original edge case scenario where constraints break.
This seems to work great except I can get the layouts to break with the following steps:
* Navigate to the "Comics to the Rescue" campaign presignup view
* Signup, then reportback - all without leaving the screen. The constraints will break (error pasted below)
Doesn't happen for other campaigns -- Comics to the Rescue has a ton of content. Also the error doesn't happen when you navigate to …

Use CampaignDetailCampaignCell for Campaign Presignup

---

Lets Do This/Controllers/Campaign/LDTCampaignDetailViewController.m
Lets Do This/Controllers/Profile/LDTProfileViewController.m
Lets Do This/Controllers/Reportback/LDTReportbackItemDetailSingleViewController.m
Lets Do This/Views/Reportback/LDTReportbackItemDetailView.h
Lets Do This/Views/Reportback/LDTReportbackItemDetailView.m
Lets Do This/Views/Reportback/LDTReportbackItemDetailView.xib

Closes #697 - renders Reportback Items with dynamic height in the Campaign Detail view controller.
Instead of using iOS self sizing cells, we manually calculate the height based on xib values in a new `-(CGFloat)heightForWidth:width` method.
I've been fighting with getting a sizing cell to return the appropriate height (#687, #688, #694), but it keeps returning sizes that are too large (and the results vary upon each load, making it even trickier). 
Reviewed with @pixelrevision -- using good ol' math (similar to what we're already doing in the `LDTCampaignDetailViewController sizeForCellAtIndexPath:` iimplementation) seems just way more understandable and maintable at this point, vs fumbling around in the dark trying to get autolayout to magically calculate the numbers via …

ReportbackItemDetailView -(CGFloat)heightForWidth:width

---

Lets Do This/Controllers/Campaign/LDTCampaignDetailViewController.m
Lets Do This/Controllers/Profile/LDTProfileViewController.m
Lets Do This/Controllers/Reportback/LDTReportbackItemDetailSingleViewController.m
Lets Do This/Views/Reportback/LDTReportbackItemDetailView.h
Lets Do This/Views/Reportback/LDTReportbackItemDetailView.m
Lets Do This/Views/Reportback/LDTReportbackItemDetailView.xib

Fixes #683 - renames the `LDTReportbackItemDetailViewDelegate` method from `didClickUserNameButtonForReportbackItemDetailView:`  to `didClickOnReportbackItemUserForReportbackItemDetailView:` - which will get called upon tapping either the User Name or User Avatar. 
It seemed like unnecessary overhead to specify two different methods (one for handling the avatar `UIImageView` and a separate for handling the User display name `UIButton`).

Clickable avatars

---

Lets Do This/Views/Reportback/LDTReportbackItemDetailView.m

Fixes https://github.com/DoSomething/LetsDoThis-iOS/issues/697#issuecomment-169218671.
* Subtracts the Caption label's left and right padding from `width` when calculating its height
* Bumps up max height to account for 3 line captions

Fixes improperly sized Reportback captions

---

Lets Do This/Controllers/Base/LDTTabBarController.h
Lets Do This/Controllers/Base/LDTTabBarController.m
Lets Do This/Controllers/Campaign/LDTCampaignListViewController.m
Lets Do This/Controllers/Cause/LDTCauseListViewController.h
Lets Do This/Controllers/Cause/LDTCauseListViewController.m
Lets Do This/Controllers/Login/LDTUserLoginViewController.m
Lets Do This/Controllers/Login/LDTUserRegisterViewController.m
Lets Do This/Controllers/Profile/LDTProfileViewController.m
Lets Do This/Models/DSOReportbackItem.m
Lets Do This/Networking/DSOUserManager.h
Lets Do This/Networking/DSOUserManager.m

Closes #714:
* refactors the `activeMobileAppCampaigns` property as `activeCampaigns`
* moves loading `activeCampaigns` to our root `LDTTabBarController` instead of the `LDTCauseListViewController`, to make it easier to switch out the initial app View Controllers (we'll want to change it to the News Feed next, the call was initially made in the `LDTCampaignListViewController`) 
* `LDTTabBarController` posts a `NSNotification` with name `activeCampaignsLoaded` when completed, or `epicFail`: a todo here is to handle it, like we did in the `LDTCampaignListViewController` with the Epic Fail VC
* `LDTCauseListViewController` adds an observer watching for the `NSNotification`

DSOUserManager.activeCampaigns

---

Lets Do This/Controllers/Base/LDTTabBarController.m
Lets Do This/Networking/DSOAPI.m

Closes #728 - we get a single User object back instead of an array from the Northstar `users/_id/:id` endpoint.
Begins basic work on #731, but needs to implement the "Try Again" button (workaround for now will be to close app)

Fix for API change

---

Lets Do This/Models/DSOCampaignSignup.m

Refs https://github.com/DoSomething/northstar/issues/210 -- we get the `reportback_data` property back from a Campaign Activity object regardless of whether a Reportback exists, it's set to null. Alters logic to check for a nested Campaign object. 
Hopefully closes #728 - missed this in #732 by not testing with a User who had any existing `campaignSignups`.

More DSOAPI changes

---

Lets Do This/Controllers/Base/LDTTabBarController.m
Lets Do This/Controllers/Onboarding/LDTOnboardingPageViewController.m
Lets Do This/Networking/DSOUserManager.h
Lets Do This/Networking/DSOUserManager.m
Lets Do This/Views/Base/LDTTheme.h

* Fixes shameful Onboarding crash (#748)
* Ends current session if we receive a 401 when trying to load the current user (logging out also results in a 401 as well). Closes #505 for now until Northstar API supports verifying a token is valid https://github.com/DoSomething/northstar/issues/186

Quick fixes

---

ReactComponent/helpers.js
ReactComponent/index.ios.js

Formats the date in the header of each post and displays the cause category.
- **helpers.js:** Added a helper module that can also be used for future general helper-like functions. For now it's just the date formatting. Take note of the "fun fact" note on JavaScriptCore's implementation of `Date`. Without changing the format from the API from `yyyy-MM-dd hh:mm:ss` to `yyyy-MM-ddThh:mm:ss`, we'd just get an invalid date and lots of undefined and NaN in the post headers instead.
- `categoryContainer`: Still learning more about flex, but it seemed like I needed to do this in order to get cause category to right-align.
- `post.categories[0]`: The `categories` field gets returned as an array even though I imagine in practice we'll just be setting one category. Here I'm just defaulting to using …

Adds cause and formats date in header of news posts

---

Lets Do This/Networking/DSOAPI.m

Count was currently to set to 200. We have 256 total as of today, bumping to 300 to avoid any confusion as to why a campaign doesn't appear.
Note: We're filtering out all closed campaigns, so there will be less than 256 available in the app.

Bump up count for loading all campaigns

---

Lets Do This/Models/DSOCause.h
Lets Do This/Models/DSOCause.m
ReactComponent/index.ios.js

Closes #756 - Adds a `DSOCause -(UIColor *)color` method to return the `UIColor` for a Cause.
Closes #766  - Adds inline styles to the News Feed via big ol `switch` statement. A very nice to have here would be sending the hex strings defined in `DSOCause` to the `NewsFeedView` component's styles via `initialProperties` - but not needed for merge.

NewsFeed Cause colors

---

Lets Do This/Controllers/Cause/LDTCauseDetailViewController.m
Lets Do This/Controllers/Cause/LDTCauseListViewController.m

Closes #727, tracks:
* `cause-list`
* `taxonomy-term/:id`

Cause Google Analytics

---

ReactComponents/NewsFeedPost.js

* Fixes #788 -- check for existence of summary item before displaying. DRY with new `renderSummaryItem` function
* Implements new design changes to resolve  #787 -- removes Subtitle, displays Title underneath the News Image
cc @jonuy ch-ch-changes

News tweaks

---

ReactComponents/Helpers.js
ReactComponents/NewsFeedPost.js

Behold:
There's a new `Helpers.convertUnicode` function that will convert unicode values in a string (`/&#[0-9]*;/g`) to the actual character. This is only applied to the post title. The problem doesn't seem to affect the summary items.
Closes #753

Converts unicode values in post titles to their human-readable form

---

ReactComponents/CauseListView.js

Adds arrow image to the Cause Detail (#799), although description still doesn't word wrap.
This has fixed height. Need to hardcode it in order to get the `causeColor` View to display (refs https://github.com/facebook/react-native/issues/3381).
Even without the color cell, I ran into difficulty getting multi-line layout to work properly with the Arrow Image, with similar things going on here: https://github.com/facebook/react-native/issues/5361#issuecomment-172282488, where using `flexDirection: row` is discouraged
iPhone 5S:

Cause List arrow image

---

Lets Do This/Controllers/Cause/LDTCauseDetailViewController.m
Lets Do This/Controllers/Cause/LDTCauseListViewController.m
Lets Do This/Controllers/News/LDTNewsFeedViewController.m

Just using a normal `self.navigationController pushViewController:animated:` isn't working when we're trying to push a View Controller with its root view set as a React Native `RCTRootView`. 
Found [this solution on SO](http://stackoverflow.com/questions/29597610/cant-push-a-native-view-controller-from-a-react-native-click/29762965#29762965) but it hardcodes the selected tab index, which is no good for something like the User Profile or Campaign Detail which could be accessed from multiple tabs. This PR changes these blocks to instead inspect our root Tab Bar Controller's selectedIndex.
Still haven't had much time to look into whether or not [this](http://stackoverflow.com/questions/29597610/cant-push-a-native-view-controller-from-a-react-native-click/29762965#29762965) is the real fix …

Use tabBarController.selectedIndex for pushing from React Native

---

Lets Do This/Models/DSOCampaignSignup.m

Checks for existence of `reportback_data` when parsing response from `user/:id/campaigns` Northstar endpoint: https://github.com/DoSomething/northstar/issues/270

Fixes Profile crash for non-public Reportbacks

---

Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Controllers/Base/LDTTabBarController.m
Lets Do This/Controllers/Campaign/LDTCampaignDetailViewController.m
Lets Do This/Controllers/Reportback/LDTSubmitReportbackViewController.h
Lets Do This/Controllers/Reportback/LDTSubmitReportbackViewController.m
Lets Do This/Controllers/User/LDTUserViewController.h
Lets Do This/Controllers/User/LDTUserViewController.m
Lets Do This/Models/DSOCampaign.m
Lets Do This/Models/DSOUser.h
Lets Do This/Models/DSOUser.m
Lets Do This/Networking/DSOAPI.h
Lets Do This/Networking/DSOAPI.m
Lets Do This/Networking/DSOUserManager.h
Lets Do This/Networking/DSOUserManager.m
ReactComponents/NewsFeedView.js
ReactComponents/ReportbackItemView.js
ReactComponents/UserView.js
index.ios.js

Begins work on the Profile Completed section (#807):
* Adds new `UserView` and `ReporbackItemView` React Components.
* Presents imagePicker / Submit Reportback screen on self profile when tapping a Doing campaign. Upon submitting a reportback, the User's profile is reloaded.
Decided to give rebuilding the Profile in React Native a try, as it seems easier to share code for networking errors if all main content-based screens are rendered with RN (#773, #620, #664). So far so good, it's definitely a lot easier (and a lot less code) for layout / self sizing content. Things aren't 100% dev complete but this is a good non-breaking place to merge into `develop` for a new release.

UserViewController: User Profile a la React Native

---

ReactComponents/UserView.js

Missed this in #815 
App crashes if the campaign doesn't exist (because it's not active). We may run into the same problem displaying reportbacks for closed campaigns also....

Filter UserView data by active campaigns

---

Lets Do This/Models/DSOCampaignSignup.h
Lets Do This/Models/DSOCampaignSignup.m
Lets Do This/Models/DSOUser.h
Lets Do This/Models/DSOUser.m
Lets Do This/Networking/DSOAPI.m
Lets Do This/Networking/DSOUserManager.m
ReactComponents/UserView.js

Refs #814 
Updates DSOAPI `- (void)loadCampaignSignupsForUser:completionHandler:errorHandler:` and `(NSString *)profileURLforUser:` to query the new Northstar Signups endpoint, as the `user/:id/campaigns` is now gone (RIP https://github.com/DoSomething/northstar/pull/273)
This blocks us from rendering Reportbacks until https://github.com/DoSomething/phoenix/issues/6151 is place.

Northstar signups endpoint

---

Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Classes/LDTAppDelegate.h
Lets Do This/Classes/LDTAppDelegate.m
Lets Do This/Controllers/Base/LDTTabBarController.h
Lets Do This/Controllers/Base/LDTTabBarController.m
Lets Do This/Controllers/Campaign/LDTCampaignViewController.h
Lets Do This/Controllers/Campaign/LDTCampaignViewController.m
Lets Do This/Controllers/Cause/LDTCauseDetailViewController.m
Lets Do This/Controllers/Cause/LDTCauseListViewController.m
Lets Do This/Controllers/LDTReactBridge.h
Lets Do This/Controllers/LDTReactBridge.m
Lets Do This/Controllers/News/LDTNewsFeedViewController.m
Lets Do This/Controllers/User/LDTUserViewController.m
Lets Do This/Models/DSOCampaign.h
Lets Do This/Models/DSOCampaign.m
Lets Do This/Models/DSOCampaignSignup.h
Lets Do This/Models/DSOCampaignSignup.m
Lets Do This/Networking/DSOAPI.h
Lets Do This/Networking/DSOAPI.m
Lets Do This/Networking/DSOUserManager.m
Lets Do This/Views/Campaign/LDTCampaignDetailCampaignCell.xib
ReactComponents/CampaignView.js
ReactComponents/CauseDetailView.js
ReactComponents/CauseListView.js
ReactComponents/NewsFeedPost.js
ReactComponents/ReportbackItemView.js
ReactComponents/Style.js
ReactComponents/UserView.js
index.ios.js

This branch is growing into a monster :japanese_ogre: , but in decent shape to merge in. Here's the dilly:
Theming changes:
* Closes #744 -- Adds `LDTCampaignViewController`, which renders the Campaign Detail in React Native and styles per new designs. Deprecates the `LDTCampaignDetailViewController`.  
* Closes #819: Uniform opaque navigationBar for all screens within our Tab Bar Controller
React Native cleanup:
* Adds a `LDTReactBridge` class to implement the `RCTBridgeModule` in a singular place, and for all React Components to use. Major DRY, and gets the `-(dispatch_queue_t)methodQueue` working, so we don't need to constantly wrap our `RCT_EXPORT_METHOD` code in [`dispatch_async(dispatch_get_main_queue())`](http://stackoverflow.com/questions/28302019/getting-a-this-application-is-modi …

LDTCampaignViewController + LDTReactBridge

---

Lets Do This/Controllers/User/LDTUserViewController.m
ReactComponents/UserView.js

Refs #757 - filter any Signups without Reportbacks which are not current and not closed from the Profile.
Still working out how to determine the relevant Signup for the Campaign view -- fighting with `AFNetworking` in Obj C vs React Native `fetch`, which relates to whether we'll post a Signup via AFNetworking or React (#829)
Also uncovered a bug which was causing the Profile to constantly query the API non-stop, so for now i'm removing the code that's doing that... which means there's bugs around logging in/out, or when you signup for a Campaign but Profile doesn't update. :construction: 
cc @jonuy -- might be useful code/logic.

Filter inactive campaign signups on Profile Doing section

---

package.json

Closes #777
Tried to upgrade to 0.20 which came out this week but was getting errors upon build, which is disturbing but doesn't seem like something we need to worry about just yet.
@jonuy @lkpttn You'll need to run [`npm install --save react-native@0.19`](https://facebook.github.io/react-native/docs/upgrading.html) in your terminal in order for `npm start` to work.

Upgrade React Native to 0.19.0

---

Lets Do This/Controllers/Campaign/LDTCampaignViewController.m
Lets Do This/Controllers/LDTReactBridge.m
Lets Do This/Models/DSOCampaign.m
Lets Do This/Models/DSOCampaignSignup.m
Lets Do This/Models/DSOReportbackItem.h
Lets Do This/Models/DSOReportbackItem.m
Lets Do This/Models/DSOUser.h
Lets Do This/Models/DSOUser.m
Lets Do This/Networking/DSOAPI.h
Lets Do This/Networking/DSOAPI.m
Lets Do This/Networking/DSOUserManager.h
Lets Do This/Networking/DSOUserManager.m
ReactComponents/CampaignView.js
ReactComponents/ReportbackItemView.js
ReactComponents/Style.js
ReactComponents/UserView.js

Queries the `signups` endpoint upon loading a `CampaignView`, and adds case to listen for a Reportback object sent from the `LDTAppDelegate.bridge` and display the Self Reportback accordingly (closes #757). This prevents a scenario where the User may signup for a campaign on the web after the app launches and an older campaign status is cached (user would have need to force quit).
Removes the `DSOUser.campaignSignups` property - was running into a lot of trouble keeping this up to date, and not worth the headache of parsing through inactive campaign runs locally for not much gain. This allows us to simplify things and kill lots of code! :fire: 
Refs #807 - completes Doing section for public profile, just need to add Share Photo button (see below)
Closes #814
TODO:

Fetch current user's activity in CampaignView.componentDidMount

---

Lets Do This/Controllers/LDTActivityViewController.h
Lets Do This/Controllers/LDTActivityViewController.m
Lets Do This/Controllers/LDTReactBridge.m
ReactComponents/CampaignView.js
ReactComponents/ReportbackItemView.js
ReactComponents/UserView.js

* Resolves #807 (and the `TODO` in #844) with last remaining feature to port over into RN -- Share photo functionality.
* Unfortunately there's not an easy way to pass the downloaded image from React Native back into Obj C, so for now the bad news is we have to re-download the image to disk upon clicking the Share button (the good news is that its then cached). Can revisit this again later, possibly check for and download reportbacks upon sign in as a background task... 
* Repurposes the `LDTActivityViewController` for re-use in News screen

Share Reportback

---

Lets Do This/Controllers/Base/LDTTabBarController.m
Lets Do This/Networking/DSOUserManager.m

The Epic Fail presented upon app launch doesn't allow you to Try Again (bug introduced when we removed the Main Feed in #725)
Closes #731: catches any network errors upon loading all campaigns and the current User in the `LDTTabBarController -(void)viewDidAppear:`
Nice to have: 
Better UX. Clicking "Try again" closes the modal, which then pops up again upon error, which also throws a `Warning: Attempt to present <UINavigationController: 0x7ff1e486fa00> on <LDTTabBarController: 0x7ff1e3d21f10> whose view is not in the window hierarchy!` Created #856 so the issue isn't gone forever.

Fixes Epic Fail on app launch

---

Lets Do This/Controllers/Login/LDTUserRegisterViewController.m
Lets Do This/Networking/DSOUserManager.m
ReactComponents/NewsFeedView.js

Uses same approach as https://github.com/facebook/react-native/issues/5224#issuecomment-184843262 to resolve #865 ungracefully.
Adds an empty `NativeAppEventEmitter ` to our initial loaded React Component, `NewsFeedView` to listen to an `eventDispatcher` we shouldn't be firing yet. Real fix here is to cleanup sending `eventDispatcher` within the `DSOUserManager` / cleanup when and how we set the current user. We set in `startSessionWithCompletionHandler` but for a newly registered user, we already set it in `createSessionWithEmail`. Fairly certain it exists in `startSessionWithCompletionHandler` for the scenario when the user is already logged in and begins a new app session.

Hotfix for RCTNativeAppEventEmitter not registered

---

Lets Do This/Controllers/Login/LDTUserRegisterViewController.m
Lets Do This/Models/DSOUser.h
Lets Do This/Models/DSOUser.m
Lets Do This/Networking/DSOUserManager.h
Lets Do This/Networking/DSOUserManager.m

With the avatar API feeling better, there isn't much need for local storage anymore -- which is originally in place to avoid non-updating issues.  Removing this for the sake of having less code to worry about..and not easily being able to access local filesystem in React Native.
Completes todo in https://github.com/DoSomething/LetsDoThis-iOS/pull/866#issuecomment-189127298

Removes deprecated local avatar storage

---

ReactComponents/NewsFeedPost.js

Refs #740 -- without the `Helpers.convertUnicode`, special characters are funky per #753

Use Helpers.convertUnicode when sharing News headline

---

Lets Do This/Networking/DSOUserManager.m
ReactComponents/UserView.js

Fixes bug introduced by #866, re-closes #847.  No need for a separate `state.photo` -- we have a `state.user.photo` property to use instead.

Fixes logout then login avatar

---

Lets Do This/Controllers/Base/LDTTabBarController.m
Lets Do This/Controllers/Campaign/LDTCampaignViewController.m
Lets Do This/Controllers/Cause/LDTCauseDetailViewController.m
Lets Do This/Controllers/LDTReactBridge.m
Lets Do This/Controllers/User/LDTUserViewController.m
Lets Do This/Models/DSOCampaign.h
Lets Do This/Models/DSOCampaign.m
Lets Do This/Models/DSOReportbackItem.m
Lets Do This/Networking/DSOAPI.h
Lets Do This/Networking/DSOAPI.m
Lets Do This/Networking/DSOUserManager.h
Lets Do This/Networking/DSOUserManager.m
ReactComponents/CampaignView.js
ReactComponents/CauseDetailView.js
ReactComponents/NetworkErrorView.js

Splitting out into a PR now to keep things readable, although it causes the Cause Detail load as empty list (in prep to begin work on #821).
* Closes #857 -- store a given Campaign into memory upon first loading, instead of loading the entire 300 campaigns upon app launch. This improves app start up time significantly for slow connections
* Makes changes to the `LDTCampaignViewController` accordingly. If we don't have the Campaign in storage, the `CampaignView` first will load with an empty `campaign` state - listening for an event of loading the campaign and then loading its gallery.
* Removes the `loadCurrentUserAndActiveCampaignsWithCompletionHander` method completely, instead we just need to load the Current User within the TabBar if we have a session saved and no loaded user.
* …

DSOUserManager cleanup

---

Lets Do This/Categories/UINavigationController+LDT.m
Lets Do This/Categories/UIViewController+LDT.m
Lets Do This/Views/Base/LDTTheme.h
Lets Do This/Views/Base/LDTTheme.m
ReactComponents/Style.js

Updates navigationBar tint to dark gray color per design (https://github.com/DoSomething/LetsDoThis-iOS/issues/819#issuecomment-182979958) 
* Defines and exports said color in `LDTTheme` to DRY
Sets navigationBar text to

Update navigationBar color

---

Lets Do This/Controllers/Login/LDTUserLoginViewController.m

Fixes #879, was previously displaying the generic "Oops our bad" message.

Display unrecognized email/password message

---

Lets Do This/Controllers/LDTReactBridge.m
Lets Do This/Controllers/Login/LDTUserLoginViewController.m
Lets Do This/Controllers/Login/LDTUserRegisterViewController.m
Lets Do This/Controllers/Reportback/LDTSubmitReportbackViewController.m
Lets Do This/Views/LDTMessage.h
Lets Do This/Views/LDTMessage.m

Closes #898 by adding a `subtitle` param to `displayErrorMessageInViewController:title:subtitle:`

Display subtitle in Signup error message

---

Lets Do This/Classes/LDTAppDelegate.h
Lets Do This/Classes/LDTAppDelegate.m
Lets Do This/Controllers/Login/LDTUserRegisterViewController.m
Lets Do This/Models/DSOUser.h
Lets Do This/Models/DSOUser.m
Lets Do This/Networking/DSOAPI.h
Lets Do This/Networking/DSOAPI.m
Lets Do This/Networking/DSOUserManager.m

Adds a `deviceTokens` array property to `DSOUser`, to store the Northstar User's `parse_installation_ids`.
Closes #45: posts device token for new users upon registration, posts device token upon login if it doesn't already exist in Northstar
Closes #166: remove the device token from the user upon logging out.

User.deviceTokens

---

Lets Do This/Controllers/LDTReactBridge.m
Lets Do This/Views/Base/LDTTheme.h
Lets Do This/Views/Base/LDTTheme.m
ReactComponents/Style.js

Attempts to fix (but doesn't) #890 -- still getting the `Unbalanced calls start/end for tag 5` warnings when navigating to a Campaign from the News Feed. 
This at least moves all of our React Bridge code into a single class, so seems worth merging in.

Move constantsToExport into LDTReactBridge

---

ReactComponents/CauseListView.js

Closes #913, closes #919 (duplicate issue)
Screenshot from 5S:

Removes description from Cause List (initial Actions screen)

---

Lets Do This/Controllers/Base/LDTTabBarController.h
Lets Do This/Controllers/Base/LDTTabBarController.m
Lets Do This/Controllers/Campaign/LDTCampaignViewController.m
Lets Do This/Controllers/Login/LDTUserLoginViewController.m
Lets Do This/Controllers/Login/LDTUserRegisterViewController.m
Lets Do This/Controllers/Settings/LDTSettingsViewController.m
Lets Do This/Controllers/User/LDTUserViewController.m
Lets Do This/Models/DSOUser.h
Lets Do This/Models/DSOUser.m
Lets Do This/Networking/DSOAPI.h
Lets Do This/Networking/DSOAPI.m
Lets Do This/Networking/DSOUserManager.h
Lets Do This/Networking/DSOUserManager.m

* Closes #911: Uses the `profile` endpoint, refactors the storage of a session token into `DSOAPI,  resolving weirdness of storing the `sessionToken` on `DSOUser`
* Fixes bug where logging in as a different user would not reset the app's different tabs to the initial screens
* Removes unnecessary 2nd network request upon submitting the login/register controllers: this was calling the `reloadCurrentUser` method, which was necessary when we were storing a user's signups locally in memory. We aren't doing that anymore -- cleanup task from #844
* Renames methods for better readability: the `DSOAPI` managed our authentication token, where as the `DSOUserManager` handles the Login, Regiser, and Logout actions.  Adds lots of inline documentation

DSOAPI.sessionToken + DSOUserManager cleanup

---

Lets Do This/Controllers/Base/LDTTabBarController.m

Implements suggestion in http://stackoverflow.com/a/34899938/1470725 to avoid app crash upon force touching a photo when selecting an avatar or Reportback image. 
Resolves #925 for short term / v1.1.0 launch.  Nice to have for a rainy day would be to implement ios9 3D touch preview things.

Hotfix for 3D touch crash

---

Lets Do This/Categories/NSDictionary+DSOJsonHelper.h
Lets Do This/Categories/NSDictionary+DSOJsonHelper.m
Lets Do This/Models/DSOCampaign.h
Lets Do This/Models/DSOCampaign.m

Closes #930 by no longer worrying if the `solutions` properties are not objects: if not, we won't display them per anticipated changes in https://github.com/DoSomething/phoenix/issues/6250.
Cleans up setting default property values within the constructor, instead of the `dictionary` accessor method.

Fixes crashing nested DSOCampaign properties

---

Lets Do This/Categories/NSError+LDT.h
Lets Do This/Categories/NSError+LDT.m
Lets Do This/Controllers/Settings/LDTSettingsViewController.m
Lets Do This/Networking/DSOUserManager.m

Closes #932 and DRY logic with new category method.

Ignore more network connection codes in Crashlytics

---

Lets Do This/Categories/NSError+LDT.h
Lets Do This/Categories/NSError+LDT.m
Lets Do This/Controllers/Login/LDTUserLoginViewController.m
Lets Do This/Controllers/Login/LDTUserRegisterViewController.m
Lets Do This/Networking/DSOAPI.h
Lets Do This/Networking/DSOAPI.m
Lets Do This/Networking/DSOUserManager.h
Lets Do This/Networking/DSOUserManager.m

Closes #945:
- New `DSOAPI` instance method `-(NSError *)errorForAPIError:(NSError *)error` takes a given `NSError` returned by `AFNetworking` , and returns a new one with a `domain` and `code` based on the failed network response sent if exists. If it doesn't it simply returns the same `NSError`.
- Adjusts accordingly view controllers to simply check for returned `error.code`, deprecates category method, `[NSError+LDT networkRequestCode]` introduced in #940 
- Moves `[CrashlyticsKit recordError:]` calls and logic out of the User Login and Register controllers and instead into the relevant `DSOUserManager` methods being called -- to keep all filtering based on code defined in this single location.
Speaking of filters, we're filtering out:
* Any network connection errors (no connection, …

[DSOAPI errorForAPIError]

---

Lets Do This/Controllers/Base/LDTTabBarController.m
Lets Do This/Controllers/News/LDTNewsFeedViewController.m

Fixes #944 -- adds `NSNotification` to only track the `news` screenView when an authenticated user exists.

News Feed Google Analytics fix

---

Lets Do This/Controllers/Campaign/LDTCampaignViewController.m
ReactComponents/UserView.js

Sets `count` query string param to display more photos on the Campaign Detail and on the Profile, per https://github.com/DoSomething/phoenix/pull/6249. Closes #941
Also adds safety check for Signups without a Campaign or Reportback. Found this one by spot checking power user [Ben Kassoy's profile](https://northstar.dosomething.org/v1/signups?user=554c2f3f469c64ed7d8b6061&count=100)
cc @jonuy @angaither

More Reportbacks

---

Lets Do This/Classes/LDTAppDelegate.m

Refactored API session token storage in `SSKeychain` for better security in #924, but forgot that `SSKeychain` entries don't get deleted from device upon app install. The `NSUserDefaults` do however (which is how we were storing the session token prior to #924)
Fixes #950 by implementing [this SO solution](http://stackoverflow.com/a/6203301/1470725).

Delete stored API session if havent onboarding #950

---

Lets Do This/Controllers/Base/LDTTabBarController.m
Lets Do This/Controllers/Login/LDTUserRegisterViewController.m
Lets Do This/Networking/DSOAPI.h
Lets Do This/Networking/DSOAPI.m
Lets Do This/Networking/DSOUserManager.h
Lets Do This/Networking/DSOUserManager.m
ReactComponents/UserView.js

* Closes #961, checking for existence of a `responseData.error` and only calling `loadSignups` if `responseData.data` exists
* Closes #958, I think. I can't replicate this but this was previously optimistic code, expecting that `data.country` would exist every time we get a response back from the API. Looks it didn't in #958, so this PR tidies up the `[DSOAPI postAvatarForUser:avatarImage:completionHandler:errorHandler:]` to return a `DSOUser`, which should be created with proper object.property checks, instead blindly trusting whatever `id` we get back from API

Safety checks on User Profile

---

Lets Do This/Classes/LDTAppDelegate.m

Fixes #969 by implementing code in https://www.parse.com/docs/ios/guide#push-notifications-tracking-pushes-and-app-opens.  Ran tests sending push notifications to just my single deviceToken and looks like we're in business:
@jonuy We're storing the deviceToken to `parse_installation_ids` (added in #912, based on Tong's initial branch in #705). Just double checking: Assume we want to store the Parse installation's `installationId` not the `deviceToken`, and that this was a bug we missed in #705 ?  
My device token is `18533d776392007005f4f0088824883ba039bad6fd36f1556e77c41f75e6ad0b`
The parse installation ID is `ed65ba7e-c828-4c3f-ab69-af8caea6cd4c`.
For user `aschachter+parse@dosomething.org`:
But this test account looks more like installation id's:
Guessing it was used to test android, …

Track Parse Push Notification opens

---

Lets Do This/Classes/LDTAppDelegate.m

The fix for #978... although we're actually not passing a `deviceToken` around but a `parseInstallationId`.. which was a mixup from #912 referencing #705. oy!
Cleanup task to rename those methods and properties, since technically it's all a `parseInstallationId`, not a `deviceToken`.  Saving for post launch.

Store parseInstallationId, not deviceToken

---

package.json

Closes #984. 
Steps to update locally:
1. `npm update` -- Updates the `node_modules` JS magic
2. `pod install` -- Updates the Objective C React Native magic
3. Success. If your simulator is [stuck in hot reloading](https://github.com/facebook/react-native/issues/6597#issuecomment-206939864), clear the reset the simulator's content and settings.

Upgrade React Native to 0.22

---

Lets Do This/Controllers/Settings/LDTSettingsViewController.m

We just needed to add `id` to the url to get it to recognize the app in the store. Fixes #986 and #987 in iTunes connect.

Fixes the "Rate DoSomething" link in the settings page

---

Lets Do This/Classes/LDTAppDelegate.m
Lets Do This/Controllers/Base/LDTTabBarController.m
Lets Do This/Models/DSOCampaign.h
Lets Do This/Models/DSOCampaign.m
ReactComponents/CampaignView.js
ReactComponents/SponsorView.js

Closes #991:
* Adds a new `NSString` property `DSOCampaign.sponsorImageURL`, populated by new `affiliates` (https://github.com/DoSomething/phoenix/pull/6395)
* hardcoded to display a single Sponsor (Campaigns may potentially need to display more than 1 in the future https://github.com/DoSomething/phoenix/issues/6396) 
* Adds a new `SponsorView` component to render a given `sponsorImageUrl`
* Got stuck on getting the sponsor logo to display to the right of the powered by without setting a fixed height and width, so adding the logo underneath the "Powered by" label for now.

Display Campaign sponsor

---

Lets Do This/Classes/LDTAppDelegate.m
Podfile

Using version 11 of Tapjoy's SDK seems to work, I show up in real time, whereas I don't using v10 (refs #999)
Here's the debug log:
````
2016-04-28 10:10:33.987 DoSomething[445:124663] [TJLog level: 4] Connect success with type:0
Apr 28 10:10:34  DoSomething[445] <Notice>: starting profile request using - 3.1-77 with options: 1fc7e
2016-04-28 10:10:34.019 DoSomething[445:124663] Tapjoy connect Succeeded
2016-04-28 10:10:36.179 DoSomething[445:124663] -canOpenURL: failed for URL: "about:blank" - error: "This app is not allowed to query for scheme about"
2016-04-28 10:10:36.188 DoSomething[445:124663] [TJLog level: 4] Events proxy is ready
````

Adds Tapjoy v11

---

Lets Do This/Classes/LDTAppDelegate.m
Podfile

Closes #970 - Upgrade looks ok -- Apparently these messages when running on Simulator are [not unexpected](https://discuss.newrelic.com/t/unable-to-remove-session-attribute/35466). Will be adding a new entry to `environments.plist` to disable.
> 2016-04-28 15:46:50.463 DoSomething[4873:37082] NewRelic(5.4.1,0x7ff73b601730):	SessionAttributeManager.cxx:315	removeSessionAttribute
Unable to remove session attribute "upgradeFrom"; attribute not found.
2016-04-28 15:46:50.463 DoSomething[4873:37082] NewRelic(5.4.1,0x7ff73b601730):	SessionAttributeManager.cxx:315	removeSessionAttribute
Unable to remove session attribute "com.newrelic.SecureUDID.returnedNil"; attribute not found.
2016-04-28 15:46:50.464 DoSomething[4873:37082] NewRelic(5.4.1,0x7ff73b601730):	SessionAttributeManager.cxx:315 …

Updates NewRelicAgent to 5.4.1

---

Lets Do This/Classes/LDTAppDelegate.m
Lets Do This/Models/DSOUser.m
Lets Do This/Networking/DSOAPI.m

* Closes #1008 - Checks for existence of keys.plist entries before passing them to relevant functions, and logs when they don't exist. 
* Refactors most use of the `[dictionary objectForKey:@"apiKey"]` method in favor of shorthand `dictionary[@"apiKey"]`

AppDelegate cleanup

---

Lets Do This/Controllers/Base/LDTWebViewController.m

Missed this in #1015 
Per [Apple docs](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIWebView_Class/#//apple_ref/occ/instp/UIWebView/scalesPageToFit):
> A Boolean value determining whether the webpage scales to fit the view and the user can change the scale.

Sets webView.scalesPageToFit

---

Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Controllers/Base/LDTReactViewController.h
Lets Do This/Controllers/Base/LDTReactViewController.m
Lets Do This/Controllers/Base/LDTWebViewController.h
Lets Do This/Controllers/Base/LDTWebViewController.m
Lets Do This/Controllers/LDTReactBridge.m
Lets Do This/Models/DSOCampaign.h
Lets Do This/Models/DSOCampaign.m
ReactComponents/ActionGuidesView.js
ReactComponents/CampaignView.js
index.ios.js

* Closes #1014 by adding a `ActionGuidesView` React component to render a Campaign's `action_guides` array as one big ol webpage, because we get formatted HTML back in the `intro.copy` and `additional_text.copy` properties.
* Concatenating all the data into a single `WebView` allows us to easily render with dynamic height (vs rendering each `copy.formatted` value as a separate `WebView` -- we'd need to specify height in each, which we'd only be able to do by calculating the `UILabel` height of each text for its font, e.g. #706) 
* Refs #1015 - Adds Google Analytics, Arrow icon (for now -- need Sketch export of file icon if we want to keep that)
* Starts on #971 by adding a `LDTReactViewController` to render our new `ActionGuidesView` component.  There's nothing about unique about this …

Campaign Resources: Action Guides

---

Lets Do This.xcodeproj/project.pbxproj
Podfile.lock
ReactComponents/ActionGuidesView.js
ReactComponents/CampaignView.js
ReactComponents/CauseDetailView.js
ReactComponents/CauseListView.js
ReactComponents/NetworkErrorView.js
ReactComponents/NetworkImage.js
ReactComponents/NewsFeedPost.js
ReactComponents/NewsFeedView.js
ReactComponents/ReportbackItemView.js
ReactComponents/SponsorView.js
ReactComponents/Style.js
ReactComponents/UserView.js
package.json

Closes #1026. They're not kidding about those breaking changes!
Starting [0.26](https://github.com/facebook/react-native/releases/tag/v0.26.0): 
> React API must be now required from `react` package

Upgrade React Native to 0.26

---

Lets Do This/Controllers/Base/LDTWebViewController.h
Lets Do This/Controllers/Base/LDTWebViewController.m
Lets Do This/Controllers/LDTReactBridge.m
ReactComponents/CampaignView.js

Closes #1031: Adds a toolbar to the `LDTWebViewController` to download file to device and creates a `UIDocumentInteractionController` to open the file.
@lkpttn -- Can you add a mock of what the button should look like? We're not tied to using the `UINavigationController.toolbar` or `UIBarButtonItem` -- this was quickest way to get up and running.

Download Campaign attachments

---

ReactComponents/UserView.js

Fixes #1028: future releases of React Native would have rendered empty profile sections since we were adding the relevant section index even if the section didn't have rows. This change only creates the section index if data exists for the relevant section.

Only adds profile section if data exists #1028

---

ReactComponents/CampaignView.js
ReactComponents/CauseDetailView.js
ReactComponents/CauseListView.js
ReactComponents/NewsFeedView.js
ReactComponents/UserView.js

Closes #906 -- no visible changes here, just removing the Android-only `colors` and `progressBackgroundColor` properties because i shoulda just [RTFM](https://facebook.github.io/react-native/docs/refreshcontrol.html#props) instead of [RATM](https://www.youtube.com/watch?v=Lp3kcHchD1Y)
Seemed easier solution is to just keep repeating the `tintColor` value vs. a separate `RefreshControl` component, as each `RefreshControl` still needs its own unique `onRefresh` and `refreshing` property values.

RefreshControl cleanup

---

Podfile.lock
package.json

Once merged, upgrade locally by:
1. `npm install`
2. `pod install`
3. open `Lets Do This.xcworkspace`

Upgrades React Native to 0.27

---

Lets Do This/Controllers/LDTReactBridge.m
Lets Do This/Models/DSOCampaign.h
Lets Do This/Models/DSOCampaign.m
Lets Do This/Networking/DSOAPI.h
Lets Do This/Networking/DSOAPI.m
ReactComponents/CampaignView.js

* Adds a new `DSOCampaign.magicLinkCopy` property and loads from API. 
* When set, our `CampaignView` renders the copy as a link that opens the Campaign up in a web browser, with our current user authenticated automagically 🐇 🎩 🔥 
* Adds Google Analytics event tracking on tap
Run this branch on Debug. Load Animals > Space Jam (campaign id 1631) and verify:
* NOTE: The Space Jam campaign will display a red warning with PHP notices that can be crossed out, and then displays a message about Global Translations are not enabled for Space Jam. That's ok for our testing purposes, the campaign is loaded. 
* Click on the Hamburger menu to go to My Account. Verify account matches your current user in iOS app.
Verify Animals > Bumble Bands has a Magic Link rendered per …

Adds Campaign Magic Link support
