Lets Do This/Base.lproj/Main.storyboard
Lets Do This/Controllers/LDTHubViewController.m
Lets Do This/Controllers/LDTRegisterViewController.h
Lets Do This/Controllers/LDTRegisterViewController.m
Lets Do This/Controllers/LDTSettingsViewController.m
Lets Do This/Models/DSOSession.h
Lets Do This/Models/DSOSession.m

Closes #1 
* Adds working logout button
* Adds skeleton Settings menu
* Adds firstName and lastName registration fields

Starting on Hub / Settings

---

Lets Do This/Base.lproj/Main.storyboard
Lets Do This/Controllers/LDTSettingsViewController.m

Makes changes documented in #13 by using Static Cells for the Account section, and removing the unnecessary segue.

Settings VC Cleanup

---

Lets Do This/Controllers/LDTRegisterViewController.m
Lets Do This/Models/DSOSession.h
Lets Do This/Models/DSOSession.m

Login params

---

Lets Do This/keys.plist
README.md

Per https://github.com/DoSomething/LetsDoThis-iOS/pull/18#issuecomment-103632814 -- devs need to locally untrack the changes if we add it into the repo.  Sooo fuhgedaboudit

Remove keys.plist from repo

---

Lets Do This/Models/DSOSession.m

Fixes for API changes

---

Lets Do This/Base.lproj/Main.storyboard
Lets Do This/Controllers/LDTRegisterViewController.h
Lets Do This/Controllers/LDTRegisterViewController.m
Lets Do This/Models/DSOSession.h
Lets Do This/Models/DSOSession.m

Closes #9 by collecting birthdate upon registration and posting to Northstar.

They say it's your birthday

---

Lets Do This/Base.lproj/Main.storyboard
Lets Do This/Controllers/LDTSettingsViewController.m

* Adds a back button, to avoid being stuck in the Settings screen
* Removes links to Change Email, Change Password, as we don't aim to support User Profile sync in a v1 release

Settings VC tweaks

---

Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Classes/AppDelegate.m
Podfile
README.md

Closes #3.  Screenshot taken by sending a global Push through the Parse web admin UI.

Parse notifications

---

Lets Do This/Base.lproj/Main.storyboard
Lets Do This/Controllers/LDTCampaignActionsViewController.m
Lets Do This/Controllers/LDTCampaignDetailViewController.h
Lets Do This/Controllers/LDTCampaignDetailViewController.m
Lets Do This/Views/LDTCampaignCollectionCell.m

Refs #51
Adds a generic Action button to the `LDTCampaignCollectionCell` and segues to an empty `LDTCampaignDetailViewController`, which now contains a property for its relevant `DSOCampaign`.

Segue to Campaign Detail VC

---

Lets Do This/Controllers/LDTCampaignActionsViewController.m
Lets Do This/Controllers/LDTTabBarController.m
Lets Do This/Models/DSOCampaign.m
Lets Do This/Models/DSOUser.m

Gets `signupFromSource` method working, blindly signing up the User whenever they click on the "Action" button for now (and blindly showing an error message too)
Refs #57

Campaign signup

---

Lets Do This/Base.lproj/Main.storyboard
Lets Do This/Controllers/LDTHubViewController.m
Lets Do This/Models/DSOUser.h
Lets Do This/Models/DSOUser.m

Creates two dictionary properties on a User, `campaignsDoing` and `campaignsCompleted`.  
Adds basic tableview sections to the Hub, re: #66 
Current implementation queries for the properties upon the `LDTTabBarController viewDidLoad`, which is probably way too much.  To be revisited in #65

Campaigns doing/completed

---

Lets Do This/Base.lproj/Main.storyboard

* Upgraded Xcode to latest version, which should hopefully avoid gratuitous changes per multiple devs working in the file. cc @tongxiang 
* Adds a `campaignDetailCell` identifier to the UITableView in the `LDTCampaignDetailViewController` to begin working on #51

 XCode update to 6.3.2

---

Lets Do This/Base.lproj/Main.storyboard
Lets Do This/Controllers/LDTCampaignDetailViewController.m
Lets Do This/Controllers/LTDPhotoCaptureViewController.m

* Adds skeleton code for the Campaign Details tableview, refs #51 
* Adds temporary camera button to segue to skeleton Photo Capture VC, to begin #74

Skeleton controllers for Proving It

---

Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Base.lproj/Main.storyboard
Lets Do This/Controllers/LDTReportbackSubmitViewController.h
Lets Do This/Controllers/LDTReportbackSubmitViewController.m

Adds Reportback Submit VC to storyboard for posting a Reportback.  All it needs now is functionality
Refs #74

Reportback Submit VC

---

Lets Do This/Controllers/LDTReportbackSubmitViewController.m
Lets Do This/Models/DSOCampaign.m

Refs #74 - sends base64 encoded image, etc but fails on #82

Post reportback (unsuccessfully)

---

Lets Do This/Info.plist
Lets Do This/Models/DSOCampaign.h
Lets Do This/Models/DSOCampaign.m

Gets rid of some RB Reviewer / Slothkit function that Ryan had ported over that we don't use anywhere.

Remove unused Slothkit methods

---

Lets Do This/Models/DSOSession.m

DSOSession Cleanup

---

Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Base.lproj/LaunchScreen.xib
Lets Do This/Classes/LDTMessage.h
Lets Do This/Classes/LDTMessage.m
Lets Do This/Controllers/LDTLoginViewController.m
Lets Do This/Controllers/LDTRegisterViewController.m
Lets Do This/Info.plist

* Adds `LDTMessage`, a subclass of `TSMessage` - closes #63 
* Checks error code for offline (refs #91)

Custom messages

---

Lets Do This/Base.lproj/Main.storyboard
Lets Do This/Controllers/LDTReportbackSubmitViewController.m
Lets Do This/Models/DSOCampaign.m

Uses newly added Campaign properties from API.

Reportback Noun/Verb

---

Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Classes/AppDelegate.m
Lets Do This/Controllers/LDTRegisterViewController.h
Lets Do This/Controllers/LDTUserConnectViewController.h
Lets Do This/Controllers/LDTUserConnectViewController.m
Lets Do This/Controllers/LDTUserRegisterViewController.h
Lets Do This/Controllers/LDTUserRegisterViewController.m
Lets Do This/Info.plist
Lets Do This/Views/LDTUserConnectView.xib
Lets Do This/Views/LDTUserRegisterFieldsView.h
Lets Do This/Views/LDTUserRegisterFieldsView.m
Lets Do This/Views/LDTUserRegisterFieldsView.xib
Lets Do This/Views/LDTUserRegisterView.h
Lets Do This/Views/LDTUserRegisterView.m
Lets Do This/Views/LDTUserRegisterView.xib

Opens pull request against a `xib-adventures` branch in the main repo, to avoid needing to pull down my fork to test.

User connect

---

Lets Do This/Networking/DSOUserManager.h
Lets Do This/Networking/DSOUserManager.m

Fixes #634 - `isCurrentUserSync` is no longer used. Thanks for finding this @tongxiang !

Remove isCurrentUserSync property 

---

Lets Do This/Views/Login/LDTUserConnectView.xib

Adds logo to User Connect

---

Podfile

Fixes #638 -- `pod update` time. 
*Ughhh stress*
*Ahhh*

Updates to Crashlytics 3.4.1

---

Lets Do This/Controllers/Login/LDTUserLoginViewController.m
Lets Do This/Networking/DSOAPI.h
Lets Do This/Networking/DSOAPI.m

Closes #469 - also refs #329 with that dot syntax

Cleanup DSOAPI methods/properties

---

Lets Do This/Controllers/Base/LDTTabBarController.m
Lets Do This/Controllers/Campaign/LDTCampaignDetailViewController.m
Lets Do This/Controllers/LDTEpicFailViewController.m
Lets Do This/Controllers/Login/LDTUserRegisterViewController.m
Lets Do This/Controllers/Onboarding/LDTOnboardingPageViewController.m
Lets Do This/Controllers/Profile/LDTUserProfileViewController.m
Lets Do This/Controllers/Reportback/LDTReportbackItemDetailSingleViewController.m
Lets Do This/Controllers/Reportback/LDTSubmitReportbackViewController.m
Lets Do This/Models/DSOCampaign.m
Lets Do This/Models/DSOCampaignSignup.m
Lets Do This/Models/DSOReportbackItem.m
Lets Do This/Models/DSOUser.m
Lets Do This/Networking/DSOAPI.m

Closes #645 by setting the instance variables directly.
I haven't been able to replicate #648 on this branch or `develop`.. which is kind of unchill :confused:

Initialization method cleanup

---

Lets Do This/Categories/UIImageView+LDT.m
Lets Do This/Categories/UINavigationController+LDT.m
Lets Do This/Categories/UIViewController+LDT.m
Lets Do This/Classes/AppDelegate.m
Lets Do This/Controllers/Base/LDTTabBarController.m
Lets Do This/Controllers/Campaign/LDTCampaignDetailViewController.m
Lets Do This/Controllers/Campaign/LDTCampaignListViewController.m
Lets Do This/Controllers/LDTEpicFailViewController.m
Lets Do This/Controllers/Login/LDTUserConnectViewController.m
Lets Do This/Controllers/Login/LDTUserLoginViewController.m
Lets Do This/Controllers/Login/LDTUserRegisterViewController.m
Lets Do This/Controllers/Onboarding/LDTOnboardingPageViewController.m
Lets Do This/Controllers/Profile/LDTUserProfileViewController.m
Lets Do This/Controllers/Reportback/LDTReportbackItemDetailSingleViewController.m
Lets Do This/Controllers/Reportback/LDTSubmitReportbackViewController.m
Lets Do This/Controllers/Settings/LDTSettingsViewController.m
Lets Do This/Views/Base/LDTButton.m
Lets Do This/Views/Campaign/LDTCampaignCollectionViewCellContainer.m
Lets Do This/Views/Campaign/LDTCampaignDetailActionButtonCell.m
Lets Do This/Views/Campaign/LDTCampaignDetailCampaignCell.m
Lets Do This/Views/Campaign/LDTCampaignListCampaignCell.m
Lets Do This/Views/LDTHeaderCollectionReusableView.m
Lets Do This/Views/Reportback/LDTReportbackItemDetailView.m

Specifically changes `[xxxx upperCaseString]` to `xxxx.upperCaseString` and `[xxxx count]` to `xxxx.count`
Closes #329. 
@aaronschachter any other instances you can think of that need to be changed?

change bracket notation to dot notation

---

Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Controllers/Profile/LDTProfileViewController.m
Lets Do This/Views/Profile/LDTProfileCampaignTableViewCell.h
Lets Do This/Views/Profile/LDTProfileCampaignTableViewCell.m
Lets Do This/Views/Profile/LDTProfileCampaignTableViewCell.xib
Lets Do This/Views/Profile/LDTProfileReportbackItemTableViewCell.h
Lets Do This/Views/Profile/LDTProfileReportbackItemTableViewCell.m
Lets Do This/Views/Profile/LDTProfileReportbackItemTableViewCell.xib

* Adds a `LDTProfileReportbackItemTableViewCell` and displays a `LDTReportbackItemDetailView` if the user has reported back for the given campaign - refs #658
* Adds the Campaign tagline to the `LDTProfileCampaignTableViewCell` - refs #659

Profile Reportbacks

---

Lets Do This/Views/Profile/LDTProfileCampaignTableViewCell.xib
Lets Do This/Views/Reportback/LDTReportbackItemDetailView.m

Missed these changes somehow in the branch I was working on in #662

Profile Cleanup

---

Lets Do This/Networking/DSOAPI.m

Adds mobile_app parameter to loadCampaigns request

---

Lets Do This.xcodeproj/project.pbxproj
Lets Do This.xcodeproj/xcshareddata/xcschemes/Debug.xcscheme
Lets Do This.xcodeproj/xcshareddata/xcschemes/Release.xcscheme
Lets Do This/Categories/NSDate+DSO.m
Lets Do ThisTests/NSDictionary+DSOJsonHelperTests.m

Add tests for NSDictionary+DSOJsonHelper. 
Tested by running `control + option + command + G`. 
Note that we had to edit the test configuration for release and debug schemes to support running tests. 
References #371.

add tests for NSDictionary+DSOJsonHelper

---

Lets Do This/Controllers/Campaign/LDTCampaignDetailViewController.m
Lets Do This/Controllers/Campaign/LDTCampaignListViewController.m
Lets Do This/Controllers/Profile/LDTProfileViewController.m
Lets Do This/Models/DSOCampaign.h
Lets Do This/Models/DSOCampaign.m
Lets Do This/Views/Campaign/LDTCampaignListCampaignCell.h
Lets Do This/Views/Campaign/LDTCampaignListCampaignCell.m
Lets Do This/Views/Campaign/LDTCampaignListCampaignCell.xib

Closes #698 - removes all "Expires in X Days" labels and related properties per latest changes.

Remove campaign.endDate / numberOfDaysLeft

---

Lets Do This/Controllers/Profile/LDTProfileViewController.m

Creates a sizing Profile Header cell in order to determine what height to render a full-height NoSignupsCel - fixes #706.

Dynamic NoSignupsCell height

---

Lets Do This/Controllers/Campaign/LDTCampaignDetailViewController.m
Lets Do This/Controllers/Profile/LDTProfileViewController.m

This functionality was only implemented on the initial Main Feed screen (`LDTCampaignListViewController`). Adds it to the Profile and Campaign Detail, as the app is still essentially unusable if the user cannot connect to a network. Closes #710

Present Epic Fail VC for network issues on Campaign Detail, User Profile

---

Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Controllers/Cause/LDTCauseDetailViewController.m
Lets Do This/Models/DSOCampaign.h
Lets Do This/Views/Cause/LDTCauseDetailCampaignCell.h
Lets Do This/Views/Cause/LDTCauseDetailCampaignCell.m
Lets Do This/Views/Cause/LDTCauseDetailCampaignCell.xib

Adds and displays a `LDTCauseDetailCampaignCell` - refs #712

Cause Detail Campaign Cell

---

Lets Do This/Views/Cause/LDTCauseDetailCampaignCell.m

Fixes failed images on Cause Detail

---

Lets Do This/Controllers/Login/LDTUserRegisterViewController.m

Dismiss HUD after creating account

---

Podfile

Update Crashlytics to 3.5.0

---

Lets Do This/Controllers/News/LDTNewsFeedViewController.m
Lets Do This/Info.plist

Fixes #752, removes the `NSAllowsArbitraryLoads` hack.

Change NewsFeed requests to HTTPS

---

Lets Do This/Info.plist

Seems to only way to fix #769 if we're supporting iOS8 (see issue comments for details)

Return of NSAllowsArbitraryLoads

---

.gitignore
Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Classes/LDTAppDelegate.m
Lets Do This/Networking/DSOAPI.h
Lets Do This/Networking/DSOAPI.m
package.json

Adds a new untracked `environment.plist` to fix #780, ending an era of making sure not to commit config changes.
TODO:

environment.plist

---

Lets Do This/Controllers/News/LDTNewsArticleViewController.h
Lets Do This/Controllers/News/LDTNewsArticleViewController.m
Lets Do This/Controllers/News/LDTNewsFeedViewController.m
ReactComponents/NewsFeedPost.js

Closes #747: Adds tracking to the News Feed and News Article screens:
* `news`
* `news/:id`

News Google Analytics

---

ReactComponents/NewsFeedPost.js

Leftovers from #792 and #789, attempts to keep style names consistent / consolidated.
Thinking about ways to implement  a `Theme` class (refs #779)

Styles cleanup

---

Lets Do This/Networking/DSOAPI.m

Closes #791. Removed from my local `keys.plist` as well and all looks good

Removes deprecated X-DS-Application-Id header field

---

Lets Do This/Categories/NSError+LDT.m

Fixes #790. Just display first error if we get multiples for now

Updates for Northstar error response

---

Lets Do This/Controllers/Cause/LDTCauseDetailViewController.m
Lets Do This/Controllers/Cause/LDTCauseListViewController.m
Lets Do This/Controllers/News/LDTNewsFeedViewController.m
Lets Do This/Models/DSOCampaign.m
Lets Do This/Models/DSOCause.h
Lets Do This/Models/DSOCause.m
Lets Do This/Networking/DSOAPI.h
Lets Do This/Networking/DSOAPI.m
ReactComponents/CauseListView.js
ReactComponents/Helpers.js
ReactComponents/NewsFeedPost.js

Updates React Native views per latest changes to the LDT News API:
* Cause hex color is returned from API, removes hardcoded values (#756)
* Displays Cause description (#713)
* Removes deprecated `activeCampaigns` property from `DSOCause` #712)
* Adds a `newsApiURL` property to `DSOAPI`
cc @jonuy 
TODO:

LDT News API updates

---

Lets Do This/Models/DSOCampaignSignup.m

Fixes #808, allows workaround described in issue to begin work on #807

Fix reportback check

---

Lets Do This/Networking/DSOAPI.m

Fixes #806 (makes changes in https://github.com/DoSomething/northstar/pull/268)
cc @DFurnes -- All looks good here, :shipit:

Updated API auth endpoints

---

Lets Do This/Networking/DSOAPI.m
Lets Do This/Networking/DSOUserManager.m

Query Signups by User ID per latest changes in https://github.com/DoSomething/northstar/pull/278
Refs #814

Back to the ol user ID

---

Lets Do This/Views/LDTMessageDefaultDesign.json

Changes the success message banner to the theme blue

---

Lets Do This/Classes/LDTAppDelegate.h
Lets Do This/Classes/LDTAppDelegate.m
Lets Do This/Controllers/Campaign/LDTCampaignViewController.m
Lets Do This/Controllers/LDTReactBridge.m
Lets Do This/Controllers/News/LDTNewsFeedViewController.m
Lets Do This/Controllers/User/LDTUserViewController.m
Lets Do This/Models/DSOCampaignSignup.m
Lets Do This/Networking/DSOAPI.m
Lets Do This/Networking/DSOUserManager.m
ReactComponents/CampaignView.js
ReactComponents/UserView.js

Creates a `RCTBridge` property in `LDTAppDelegate` to get React Native's `bridge.eventDispatcher sendAppEventWithName:body` working: `CampaignView` and `UserView` update upon campaign signup.
Refs #757

LDTAppDelegate.bridge

---

Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Controllers/Cause/LDTCauseListViewController.m
Lets Do This/Controllers/News/LDTNewsFeedViewController.m
Lets Do This/Info.plist
Lets Do This/Views/Settings/LDTSettingsView.xib

Closes #830 
TODO: Rename this repo to something such that our `LDT` prefix still makes sense, maybe something like Lieutenant Dan Terminator?
cc @weerd

Change app title to DoSomething

---

ReactComponents/UserView.js

Closes #656 for sake of getting to a stable release.
Nice to haves:

Empty Profile

---

ReactComponents/CampaignView.js
ReactComponents/CauseListView.js
ReactComponents/NetworkErrorView.js
ReactComponents/NewsFeedView.js
ReactComponents/UserView.js

Adds new React Component to inform when a network error has occurred, and prompts user to tap to retry loading.
* Closes #773 
* Closes #664 
* Closes #620
TODO: 
* DRY the Loading Views.. potentially refactor this as just a `NetworkRequestView` to handle both?

NetworkErrorView

---

Podfile

Updates Crashlytics to 3.7.0

---

ReactComponents/UserView.js

Closes #659 by adding last remaining item, the arrows.
Running into issues vertically centering the arrow without setting the row height. It's a little bit hacked right now to display close enough to center, but a few pixels off :confused:

Add arrows to Profile Doing rows

---

Lets Do This/Controllers/User/LDTUserViewController.m
Lets Do This/Networking/DSOAPI.h
Lets Do This/Networking/DSOAPI.m
Lets Do This/Networking/DSOUserManager.m
ReactComponents/UserView.js

Fixes #847, which was introduced by #815. Kills code we're no longer using. :fire:

Update current user upon logging in with different account

---

Lets Do This/Controllers/Base/LDTTabBarController.m
Lets Do This/Networking/DSOUserManager.m
ReactComponents/UserView.js

Timestamp cache bustin' handled in API now: https://github.com/DoSomething/northstar/pull/288

Remove appended timestring

---

Lets Do This/Models/DSOCampaign.h
Lets Do This/Models/DSOCampaign.m
ReactComponents/CampaignView.js

Updates copy for a closed campaign (which can be found via News Feed Post, or a Reportback on a Profile), last remaining item to resolve #822  
Also updates copy in case a SMS game is linked to (#813) -- this could happen if an editor links a News Post to a SMS Game if/when we implement #857 . cc @jonuy

Closed Campaign view

---

ReactComponents/CauseDetailView.js

Picks up where #878 left off: loading all Campaigns tagged with a given Cause from the API to close #821.
TODO Bonus edition

Load all campaigns tagged with a Cause

---

Lets Do This/Controllers/Cause/LDTCauseDetailViewController.m
ReactComponents/CauseDetailView.js

Fixes bug I missed in #881, also sets count to 100 campaigns (default of 25 is too small for some Causes)

Fixes presenting Campaign, load more Campaigns

---

Lets Do This/Controllers/Base/LDTBaseViewController.m

Calls stopListeningForNotifications to remove observers

---

ReactComponents/UserView.js

Centers header content

---

ReactComponents/CampaignView.js
ReactComponents/Helpers.js
ReactComponents/UserView.js

Fixes #888 by making sure a Reportback Item exists within a Signup's Reportback.
If the Reportback is corrupt, the Signup is displayed within the "Actions I'm Doing" section... hmm which actually means we'll need to check for the existence of a Reportback Item in the `CampaignView` too.

Adds checks for corrupt Reportbacks

---

Lets Do This/Controllers/Login/LDTUserLoginViewController.m

Login password validation

---

ReactComponents/CampaignView.js

The ol `if else` trick. Fixes #895

Adds missing else to fix closed campaign state

---

Lets Do This/Controllers/Login/LDTUserRegisterViewController.m
Lets Do This/Networking/DSOUserManager.m

Closes #759. Here's the log from an instance of [Crashlytics issue 29](https://fabric.io/do-something/ios/apps/org.dosomething.LetsDoThis/issues/56d74325f5d3a7f76b4131c3) -- which is from submitting a reportback to a closed campaign (#895)
````
0 | 23:59:44:192 | -[DSOUserManager continueSessionWithCompletionHandler:errorHandler:] line 114 $ user 56d74a93b06a45373b8b4592
1 | 23:59:48:176 | -[DSOUserManager loadAndStoreCampaignWithID:completionHandler:errorHandler:] line 219 $ campaign 1144
2 | 23:59:48:229 | __76-[DSOUserManager loadAndStoreCampaignWithID:completionHandler:errorHandler:]_block_invoke line 221 $ stored
3 | 23:59:50:187 | -[DSOUserManager signupUserForCampaign:completionHandler:errorHandler:] line 156 $ campaign 1144
4 | 23:59:50:655 | -[DSOUserManager …
```

Adds Crashlytics logging

---

Lets Do This/Views/Login/LDTUserLoginView.xib
Lets Do This/Views/Login/LDTUserRegisterView.xib

Disable autocorrect on login/registration screens

---

Lets Do This/Controllers/Settings/LDTSettingsViewController.m

Removes edit_requested param from Feedback form link

---

Lets Do This/Categories/NSDictionary+DSOJsonHelper.h
Lets Do This/Categories/NSDictionary+DSOJsonHelper.m
Lets Do This/Categories/NSError+LDT.m
Lets Do This/Models/DSOCampaign.m
Lets Do This/Models/DSOCampaignSignup.m
Lets Do This/Models/DSOCause.m
Lets Do This/Models/DSOReportbackItem.m
Lets Do This/Models/DSOUser.m

Closes #247, cleans up `DSOCampaign -(instancetype)initWithDict:`

Cleanup NSDictionary+DSOJsonHelper #247

---

Lets Do This/Classes/LDTAppDelegate.m

Fixes #926, any time user opens the app we set badges to 0 for v1.1

Badges be gone

---

ReactComponents/Helpers.js
ReactComponents/ReportbackItemView.js

Closes #721. Created an "Everything is Null" test campaign on staging, and submitted a reportback with an email first name to test.
cc @jonuy

Mask first names containing email addresses on Reportbacks

---

ReactComponents/UserView.js

Sort Profile in descending order

---

Lets Do This/Categories/GAI+LDT.m
Lets Do This/Controllers/Base/LDTTabBarController.m
Lets Do This/Networking/DSOUserManager.m
ReactComponents/UserView.js

Refs #935 - (first introduced in #902).
Also implements `UITabBarControllerDelegate` to log Tab Bar Controller changes.
Example log (non-fatal error occurs at line 26)
> 0	|	19:24:01:775	|	__68-[DSOUserManager continueSessionWithCompletionHandler:errorHandler:]_block_invoke line 132 $ user 563bb421469c64d9058b4644
1	|	19:24:01:776	|	-[GAI(LDT) trackScreenView:] line 19 $ news
2	|	19:24:04:303	|	-[LDTTabBarController tabBarController:didSelectViewController:] line 255 $ selectedIndex 2
3	|	19:24:04:352	|	-[GAI(LDT) trackScreenView:] line 19 $ user-profile/self
4	|	19:24:06:281	|	__76-[DSOUserManager loadAndStoreCampaignWithID:completionHandler:errorHandler:]_block_invoke line 250 $ campaign 73
5	|	19:24:06:771	|	-[GAI(LDT) trackScreenView:] line 19 $ campaign/73
6	|	19:24:09:972	| …

Log GoogleAnalytics screenView & event values to Crashlytics

---

Lets Do This/Controllers/Campaign/LDTCampaignViewController.m

Refs #949, which was perhaps too bold, like that Prince song. 
100 seems a bit much on slower connections. Let's try 50 for v1.1

Less Reportbacks

---

Lets Do This/Controllers/Settings/LDTSettingsViewController.m
Lets Do This/Info.plist
Lets Do This/Views/Settings/LDTSettingsView.xib

Closes #959, removes `UISwitch` and relevant check for  `currentUserNotificationSettings`.

Settings tweaks

---

ReactComponents/CampaignView.js

It's become my personal code of honor to include this image every time I open a pull request for copy changes.

Update copy for SMS Game, closes #960

---

Lets Do This/Controllers/Settings/LDTSettingsViewController.m
Lets Do This/Views/Settings/LDTSettingsView.xib

Adds links to Privacy Policy and Terms of Service to Settings screen to close #982. This PR is a gr8 example of why i :heart: React Native these days

Settings links to Terms of Service, Privacy Policy

---

Lets Do This/Networking/DSOAPI.m

Updates LDTSOURCENAME to fix #990

---

Lets Do This/Controllers/Base/LDTBaseViewController.h
Lets Do This/Controllers/Base/LDTBaseViewController.m
Lets Do This/Controllers/Login/LDTUserLoginViewController.m
Lets Do This/Controllers/Login/LDTUserRegisterViewController.m

Closes #993 -- lets the API handle email validation, DRY / hack the 🌎

Removes email validation from View Controllers

---

Lets Do This/Models/DSOCampaign.m

Hardcoded sponsor logo

---

Lets Do This.xcodeproj/project.pbxproj
Lets Do This/Controllers/Base/LDTWebViewController.h
Lets Do This/Controllers/Base/LDTWebViewController.m
Lets Do This/Controllers/LDTReactBridge.m
Lets Do This/Models/DSOCampaign.h
Lets Do This/Models/DSOCampaign.m
ReactComponents/CampaignView.js

Starts work on #1014, unblocked by new Campaign `attachments` property, added in https://github.com/DoSomething/phoenix/pull/6434. Adds a new `LDTWebViewController` class which renders a given URL in a `UIWebView`.
cc @lkpttn

Campaign Resources: Attachments

---

Lets Do This/Networking/DSOAPI.m

Update Pantheon url

---

ReactComponents/NetworkImage.js

Hotfix for #1013 -- comments out NetworkImage onProgress handler

---

Lets Do This/Controllers/Base/LDTWebViewController.h
Lets Do This/Controllers/Base/LDTWebViewController.m
Lets Do This/Controllers/LDTReactBridge.m
ReactComponents/CampaignView.js

Include Campaign attachment id in Google Analytics tracking

---

Podfile
Podfile.lock

Updates Crashlytics to 3.7.1

---

ReactComponents/CampaignView.js
ReactComponents/CauseDetailView.js
ReactComponents/CauseListView.js
ReactComponents/NetworkLoadingView.js
ReactComponents/NewsFeedView.js
ReactComponents/UserView.js

Refs #906 - adds a new `NetworkLoadingView` component for some much needed DRY
.

DRY: NetworkLoadingView

---

Lets Do This/Models/DSOCampaign.m
ReactComponents/CauseDetailView.js
ReactComponents/SponsorView.js

* Closes #1002 
* Fixes failed propType warning in `CauseDetailView.js`

SponsorView background color change
